### ISSUE TITLE
multiple markers from multiple sources

### ISSUE THREAD

**Issue by faysal515** [pubnub/pubnub-mapbox#24]
I want to display multiple markers data coming from multiple channels. is it possible? here's my data structure of my message

```javascript
[{
latlng: [1.00,1.00]
}]
```

right now if I initialize my constructor like below, no matter which channels my data comes from, only one marker is rendered on the map and updated

```javascript
var map = eon.map({
          pubnub: pn,
          id: 'map',
          options: {
          center: [23.7167498, 90.4154881], // [lat, lng]
          zoom: 14,
          },
          mbToken: '....',
          mbId: '....',
          channels: ['bus-01','bus-02']
        });
```

**Comment by ianjennings** [comment]
This is an example of using two different publishing sources:
https://github.com/pubnub/eon-map/blob/master/examples/distributed.html

You need to supply a unique key parameter for your latlng. Try using objects instead:

```js
{myKey: {
latlng: [1.00,1.00]
}}
```
