### ISSUE TITLE
Ability to globally change certain marker styles after adding?

### ISSUE THREAD

**Issue by chrismanderson** [pubnub/pubnub-mapbox#5]
Ideally, I'd like to be able to loop through and fade/change the color for all markers that haven't been updated after a certain time. Is this possible with the current Eon framework?

**Comment by ianjennings** [comment]
Check out the `marker` function [within the EON config](https://github.com/pubnub/eon-map#init). You 
can use this create custom markers. You could pair this with a "setTimeout()" to change the marker color over time.

In addition, the `eon.map()` function returns a [Mapbox](http://mapbox.com) object. Alternatively, you can use the mapbox object to get markers and update them according to your needs.
