### ISSUE TITLE
Approximate the lo

### ISSUE THREAD

**Issue by nikhilbansal** [pubnub/pubnub-mapbox#8]
I have a set of latitude and longitude with their timestamps at which they were captured. I wish to animate a vehicle on the map using these data points. Is there any way to correct the location to the nearest road if the location is a bit away from the road ?

**Comment by ianjennings** [comment]
You might be able to use Mapbox streets to do this? 
https://www.mapbox.com/vector-tiles/mapbox-streets-v7/

You would use the ```transform``` callback to edit the lat/long of the marker (and move it onto the road) before it was rendered.
